### ISSUE TITLE
Experiment freezes after it's been interrupted by the safeguards

### ISSUE THREAD

**Issue by WixoLeo** [chaostoolkit/chaostoolkit#210] opened 2021-03-03 11:53 UTC
**Describe the bug**
When the tolerance of one of the probes is falsy, sometimes the experiment just freezes. It's unreliable.

![image](https://user-images.githubusercontent.com/52653470/109814156-d6473080-7c36-11eb-92ff-523c0b565a86.png)

**Runtime versions**
```
$ python --version
Python 3.8.0

$ chaos info core
NAME                VERSION   
CLI                 1.9.0     
Core library        1.19.0  

$ chaos info extensions
NAME                                    VERSION   LICENSE                       DESCRIPTION                                       
chaostoolkit-addons                     0.1.3     UNKNOWN                       Addons for your Chaos Toolkit experiments 
```

**To Reproduce**

1. Create a `exp.json`
2. Put this code in there:
```json
{
  "version": "1.0.0",
  "title": "test",
  "description": "test",
  "configuration": {
    "myarg": "exp.json",
    "another_arg": "another.json"
  },
  "tags": [
    "network",
    "lala"
  ],
  "controls": [
    {
      "name": "Safeguards",
      "provider": {
        "type": "python",
        "module": "chaosaddons.controls.safeguards",
        "arguments": {
          "probes": [
            {
              "name": "My probe",
              "description": "My best probe",
              "tolerance": {
                "type": "regex",
                "pattern": "exp.jsonnn",
                "target": "stdout"
              },
              "type": "probe",
              "provider": {
                "type": "process",
                "path": "echo",
                "arguments": "${myarg}"
              },
              "pauses": {
                "after": 1
              }
            }
          ]
        }
      }
    }
  ],
  "steady-state-hypothesis": {
    "title": "Check something",
    "probes": [
      {
        "name": "My probe",
        "description": "My best probe",
        "tolerance": {
          "type": "regex",
          "pattern": "exp.json",
          "target": "stdout"
        },
        "type": "probe",
        "provider": {
          "type": "process",
          "path": "echo",
          "arguments": "${myarg}"
        }
      }
    ]
  },
  "method": [
    {
      "name": "My probe",
      "description": "My best probe",
      "tolerance": {
        "type": "regex",
        "pattern": "exp.json",
        "target": "stdout"
      },
      "type": "probe",
      "provider": {
        "type": "process",
        "path": "echo",
        "arguments": "${myarg}"
      },
      "pauses": {
        "after": 1
      }
    }
  ],
  "rollbacks": [
    {
      "name": "My probe",
      "description": "My best probe",
      "tolerance": {
        "type": "regex",
        "pattern": "exp.json",
        "target": "stdout"
      },
      "type": "probe",
      "provider": {
        "type": "process",
        "path": "echo",
        "arguments": "${myarg}"
      },
      "pauses": {
        "after": 1
      }
    }
  ]
}
```
3. Run command multiple times 
```chaos run exp.json --rollback-strategy always```

**Expected behavior**
It should complete the experiment.

**Comment by Lawouach** [comment] 2021-03-03 14:24
I managed to reproduce this but this may take some work to figure what's going on. Remember that the harsh interruption provided by CTK is not deterministic because it interacts with the Python VM in a way that isn't friendly.

I need to see if I can profile this piece of code.

**Comment by WixoLeo** [comment] 2021-03-03 15:43
> I managed to reproduce this but this may take some work to figure what's going on. Remember that the harsh interruption provided by CTK is not deterministic because it interacts with the Python VM in a way that isn't friendly.
> 
> I need to see if I can profile this piece of code.

No problem, thank you!

**Comment by WixoLeo** [comment] 2021-03-09 13:13
Hi! Is there any progress with this? @Lawouach

**Comment by Lawouach** [comment] 2021-03-14 20:36
It's a tricky one as we are doing some stuff that are on the edge of what the python VM allows.

This may be also due to a subtle bug in Python that has recently been fixed and may not be available to the Python vm you are running:

https://github.com/python/cpython/commit/242c26f53edb965e9808dd918089e664c0223407
https://bugs.python.org/issue31783

**Comment by Lawouach** [comment] 2021-03-14 20:48
I just tried with Python3.9 and it seems to work fine because it contains the fix above. It may be backported to 3.7 and 3.8. Are you in a position to upgrade? I'm not sure I can find a fix from CTK itself.

**Comment by WixoLeo** [comment] 2021-03-24 10:55
I've upgraded to python 3.9.2 and it's still the same issue. At the same time I've found something bad that's happening (not only on python3.9 but also in previous versions) is that sometimes when safeguard attemts to stop the experiment, it sometimes ignores the signal and continues to the methods, which is very bad. We have prechecks in the experiment that check if the experiment should run or not. And if one of the prechecks is failing, it should stop.

Here is a log:
```
[2021-03-24 12:52:05 CRITICAL] Safeguard 'My probe' triggered the end of the experiment
[2021-03-24 12:52:05 INFO] Playing your experiment's method now...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/chaoslib/exit.py", line 147, in _leave_now
    logger.warning("Caught signal num: '{}'".format(signum))
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 1454, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.handleError(record)
  File "/Users/leonidh/.pyenv/versions/3.9.2/lib/python3.9/logging/__init__.py", line 1000, in handleError
    sys.stderr.write('--- Logging error ---\n')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/chaostoolkit/cli.py", line 187, in run
    journal = run_experiment(
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/chaoslib/caching.py", line 76, in wrapped
    return f(**arguments)
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/chaoslib/experiment.py", line 129, in run_experiment
    return runner.run(
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/chaoslib/run.py", line 310, in run
    journal = self._run(
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/chaoslib/run.py", line 373, in _run
    state = run_method(
  File "/Users/leonidh/Documents/repos/chaosworkspace/chaos-hub-cli/chaoshub-venv/lib/python3.9/site-packages/chaoslib/run.py", line 553, in run_method
    logger.info("Playing your experiment's method now...")
Message: "Playing your experiment's method now..."
Arguments: ()
[2021-03-24 12:52:05 INFO] Probe: My probe
[2021-03-24 12:52:05 WARNING] Rollbacks were explicitly requested to be played
```

After some investigation it turns out that the signal is being caught by the python's logger in the exception handler and it doesn't do anything with it. Therefore the experiment continues I think.

What do you think?

**Comment by Lawouach** [comment] 2021-03-24 11:00
Oh thanks for investigating further. This one is so tricky to go through with the interruptions (signals that is).

I'll try to understand why the logger does so.

**Comment by WixoLeo** [comment] 2021-03-24 11:03
> Oh thanks for investigating further. This one is so tricky to go through with the interruptions (signals that is).
> 
> I'll try to understand why the logger does so.

Yes, it's sad that signals are this much unreliable..

Thank you for helping us! Waiting for your findings!

**Comment by Lawouach** [comment] 2021-03-24 11:08
The difficult part really is the fact they can't be trusted by nature. I wish the Python VM had a reliable mechanism to exit, even blocking calls. But it doesn't and signals are a poor's man solution for now. It's also hard because we have to still play the rollbacks so it's not just an idea of terminating the process.

**Comment by WixoLeo** [comment] 2021-07-12 14:19
Update @Lawouach :
I've removed `log.warning` from `chaoslib.exit` function `_leave_now()`
And ran the experiment about 50 times, and it worked as expected every single time. So weird.

**Comment by Lawouach** [comment] 2021-07-12 14:40
With what you had found in https://github.com/chaostoolkit/chaostoolkit/issues/210#issuecomment-805719761, I'm not entirely surprised. Could you do a small PR to remove it (with a changelog entry) and i'll merge it. We can start from here?

**Comment by WixoLeo** [comment] 2021-07-12 14:53
@Lawouach https://github.com/chaostoolkit/chaostoolkit-lib/pull/221

**Comment by CharlieMoon37** [comment] 2021-08-06 15:03
Issue resolved, branch merged but issue was not closed

**Closed** 2021-08-06 15:03 UTC
Labels: core
