### ISSUE TITLE
boolean in 'tolerance' does not seem to work correctly

### ISSUE THREAD

**Issue by 0rc** [chaostoolkit/chaostoolkit#72] opened 2018-08-22 13:05 UTC
It is mentioned in [doc](https://docs.chaostoolkit.org/reference/api/experiment/) that 'tolerance' supports boolean.
Quote:
A boolean tolerance:
`
"tolerance": true
`

If I put it like that in experiment json like that it fails:

$ chaos run experiment-asg.json 
Traceback (most recent call last):
  File "/home/dima/.venvs/chaostk/bin/chaos", line 11, in <module>
    sys.exit(cli())
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/chaostoolkit/cli.py", line 124, in run
    experiment = load_experiment(click.format_filename(source), settings)
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/chaoslib/loader.py", line 76, in load_experiment
    return parse_experiment_from_file(experiment_source)
  File "/home/dima/.venvs/chaostk/lib/python3.6/site-packages/chaoslib/loader.py", line 31, in parse_experiment_from_file
    return json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 42 column 30 (char 1376)

Please advice if this is the bug in docs or elsewhere

meanwhile I have workaround adding str() for the functions that return boolean value

**Comment by 0rc** [comment] 2018-08-23 09:15
however, this works perfectly with yaml so the problem is only related to json

**Comment by Lawouach** [comment] 2018-08-23 13:37
Hey @0rc, now that's odd because I've used `true` in the past wouthout trouble in JSON experiments.

Could you have some odd space characters around `true`? I am asking because to me all the time when I actually input some sort of insecable space that looks normal at first sight but is obviously not valid when parsing.

**Comment by Lawouach** [comment] 2018-09-18 11:28
Hey @0rc, did you reproduce this issue or was it just a glitch? May we close this if it was?

**Closed** 2020-06-04 11:24 UTC
